### ISSUE TITLE
Python 2.6 compatibility

### ISSUE THREAD

**Issue by marcinn** [lxyu/supervisor-quick#1]
Hey,

Thanks for very useful plugin! It would be nice to male it compatible with python 2.6.
Process name formatting raises ValueError in 2.6 when trying to (re)start or stop a process (https://github.com/lxyu/supervisor-quick/blob/master/supervisor_quick.py#L32)
This may be an issue in other places using new-style str formatting.

Issue reported on Python 2.6.6 (r266:84292, Sep 11 2012, 08:34:23) [GCC 4.4.6 20120305 (Red Hat 4.4.6-4)] with supervisor_quick==0.1.1

Steps to reproduce:
- install Python 2.6.6
- pip install supervisor-quick==0.1.1 (within 2.6.6 environment)
- configure supervisor as described in plugin instruction
- open supervisorctl
- call `start <processname>`
- exception should be raised:

```
error: <type 'exceptions.ValueError'>, zero length field name in format: file: /path/to/env/eggs/supervisor_quick-0.1.1-py2.6.egg/supervisor_quick.py line: 30
```

**Comment by lxyu** [comment]
"zero length field name" error fixed. :)

**Comment by marcinn** [comment]
:beer:
