### ISSUE TITLE
Seems that it doesn't work for me

### ISSUE THREAD

**Issue by PavloPoliakov** [lxyu/supervisor-quick#3]
Hi,

I've encountered the problem of the long start/stop by supervisor so decided to try your plugin.

I've installed it using pip and adjusted the supervisor.conf file:

```
...content
[include]
files = /etc/supervisor/conf.d/*.conf

[ctlplugin:quick]
supervisor.ctl_factory = supervisor_quick:make_quick_controllerplugin
...content
```

But when I use it, it seems that it doesn't work:
![image](https://cloud.githubusercontent.com/assets/839290/3795704/6d1e673e-1bbe-11e4-8564-9cc510f57342.png)

However it does accept the 'quick*' command, which means that the plugin is loaded, as I understand.

Any thoughts how could I make it work?

**Comment by lxyu** [comment]
This is a bug in current implementation. Currently it treats all program as group.

Workaround: add a `:` at the end of program.

``` bash
> quickstart logstash:
```

This bug expected to be fixed in near future.. when I got some spare time.

**Comment by PavloPoliakov** [comment]
Good, nice.

Thanks for the plugin!
