### ISSUE TITLE
supervisor-quick does not work.Please help!

### ISSUE THREAD

**Issue by tnajun** [lxyu/supervisor-quick#5]
supervisor-quick does not work.
My environment is this.
・Python (2.7.5)
・supervisor (3.1.3)
・supervisor-quick (0.1.4)

'supervisorctl quickstart application-name'  is carried out, no reaction.
When 'supervisorctl status' checked, it still stop.
Even if the log is made a debug mode, nothing is output.

**Comment by lxyu** [comment]
try add a `:` after the application-name

`supervisorctl quickstart application-name:`

this is a bug in supervisor-quick that it only works for process group.. to be fixed..

**Comment by tnajun** [comment]
Thank you. And I tried it and it run.
It works about 1% faster. How much faster would it be compared to the default stop and start?

**Comment by lxyu** [comment]
It works best when stop and start takes tens of seconds...If you don't feel the default start/stop slow, don't use it~
